### ISSUE TITLE
After a while, PostNL API no longer responds, need to update password?

### ISSUE THREAD

**Issue by koenrijpkema** [peternijssen/lovelace-postnl-card#22]
Had this happen before, after a month orso, the API no longer lets the component login: 

Can't connect to the PostNL API
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/postnlpy/postnlapi.py", line 179, in _request_login
    data = response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/postnl/sensor.py", line 43, in setup_platform
    api = PostnlApi(username, password, refresh_rate.total_seconds())
  File "/usr/local/lib/python3.7/site-packages/postnlpy/postnlapi.py", line 62, in __init__
    self._request_login()
  File "/usr/local/lib/python3.7/site-packages/postnlpy/postnlapi.py", line 182, in _request_login
    raise (UnauthorizedException())
postnlpy.postnlapi.UnauthorizedException

However, if I test the login details, they work fine on the website. I can get the component to work again, if I change my password.

**Comment by peternijssen** [comment]
The PostNL component seems to be broken. See https://github.com/home-assistant/home-assistant/issues/28726

**Comment by koenrijpkema** [comment]
Still broken in 102.1 for me:

Fri Nov 22 2019 12:17:19 GMT+0100 (Central European Standard Time)
Can't connect to the PostNL API
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/postnlpy/postnlapi.py", line 179, in _request_login
    data = response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/postnl/sensor.py", line 43, in setup_platform
    api = PostnlApi(username, password, refresh_rate.total_seconds())
  File "/usr/local/lib/python3.7/site-packages/postnlpy/postnlapi.py", line 62, in __init__
    self._request_login()
  File "/usr/local/lib/python3.7/site-packages/postnlpy/postnlapi.py", line 182, in _request_login
    raise (UnauthorizedException())
postnlpy.postnlapi.UnauthorizedException

**Comment by IIIdefconIII** [comment]
same here + three collegues, all the same error

**Comment by JanLankhorst** [comment]
Same here, a solution or workaround would be nice

**Comment by peternijssen** [comment]
Just follow this thread; https://github.com/home-assistant/home-assistant/issues/28726

Closing this issue as it's part of HA and not the card.
